version: '3.7'

services:
  api:
    image: devbytom/dsock-api:latest
    build:
      dockerfile: api/Dockerfile
      context: .
      target: development
    volumes:
      - .:/app
      - /app/api/build/
    ports:
      - 3000:80
    depends_on:
      - redis
  worker:
    image: devbytom/dsock-worker:latest
    build:
      dockerfile: worker/Dockerfile
      context: .
      target: development
    volumes:
      - .:/app
      - /app/worker/build/
    ports:
      - 3001:80
    depends_on:
      - redis
  redis:
    image: redis:alpine
    ports:
      - 3002:6379
